# =====================================================
# FILE: 02_PIPELINE_AND_CODE/transfromation/dbt/dbt_project.yml
# =====================================================
name: 'tax_pipeline_transform'
version: '1.0.0'
config-version: 2

profile: 'tax_pipeline_profile'
model-paths: ["models"]
macro-paths: ["macros"]

models:
  tax_pipeline_transform:
    # Models in models/clean/ will go to: silver_clean_transformations datasets
    clean:
      +materialized: table
      +schema: silver_clean_tax_forms # UPDATED
    
    # Models in models/mart/ will go to: gold_mart_crm datasets
    mart:
      +materialized: table
      +schema: gold_crm_ready_data # UPDATED
